<?php
declare(strict_types=1);

namespace ipad54\BedrockEditionClient\network;

use ipad54\BedrockEditionClient\Client;
use ipad54\BedrockEditionClient\network\handler\PreSpawnPacketHandler;
use ipad54\BedrockEditionClient\network\raknet\RakNetConnection;
use ipad54\BedrockEditionClient\player\LoginInfo;
use ipad54\BedrockEditionClient\player\Player;
use ipad54\BedrockEditionClient\utils\KeyPair;
use ipad54\BedrockEditionClient\utils\Utils;
use pocketmine\entity\Location;
use pocketmine\network\mcpe\compression\Compressor;
use pocketmine\network\mcpe\encryption\EncryptionContext;
use pocketmine\network\mcpe\encryption\EncryptionUtils;
use pocketmine\network\mcpe\handler\PacketHandler;
use pocketmine\network\mcpe\JwtUtils;
use pocketmine\network\mcpe\protocol\ClientboundPacket;
use pocketmine\network\mcpe\protocol\LoginPacket;
use pocketmine\network\mcpe\protocol\MovePlayerPacket;
use pocketmine\network\mcpe\protocol\Packet;
use pocketmine\network\mcpe\protocol\PacketPool;
use pocketmine\network\mcpe\protocol\PlayerAuthInputPacket;
use pocketmine\network\mcpe\protocol\ProtocolInfo;
use pocketmine\network\mcpe\protocol\serializer\ItemTypeDictionary;
use pocketmine\network\mcpe\protocol\serializer\PacketBatch;
use pocketmine\network\mcpe\protocol\serializer\PacketSerializerContext;
use pocketmine\network\mcpe\protocol\ServerboundPacket;
use pocketmine\network\mcpe\protocol\StartGamePacket;
use pocketmine\network\mcpe\protocol\TextPacket;
use pocketmine\network\mcpe\protocol\types\ItemTypeEntry;
use pocketmine\network\mcpe\protocol\types\login\ClientDataPersonaPieceTintColor;
use pocketmine\network\mcpe\protocol\types\login\JwtChain;
use pocketmine\network\mcpe\protocol\types\PlayMode;
use pocketmine\network\PacketHandlingException;
use raklib\utils\InternetAddress;
use pocketmine\network\mcpe\protocol\serializer\PacketSerializer;
use pocketmine\network\mcpe\protocol\types\login\ClientDataAnimationFrame;
use pocketmine\network\mcpe\protocol\types\login\ClientDataPersonaSkinPiece;
class NetworkSession{
	private const MTU = 1492;

	private InternetAddress $serverAddress;
	private LoginInfo $loginInfo;

	private Client $client;

	private RakNetConnection $connection;
	private ?Compressor $compressor = null;

	private ?EncryptionContext $cipher = null;

	private \Logger $logger;

	private PacketSerializerContext $serializerContext;
	private PacketPool $packetPool;
	private ?PacketHandler $handler = null;

	private ClientPacketSender $sender;

	private ?Player $player = null;

	private KeyPair $keyPair;

	private bool $loggedIn = false;

	public function __construct(InternetAddress $serverAddress, LoginInfo $loginInfo, Client $client){
		$this->serverAddress = $serverAddress;
		$this->loginInfo = $loginInfo;
		$this->client = $client;

		$this->logger = $client->getLogger();

		$this->packetPool = PacketPool::getInstance();
		$this->serializerContext = new PacketSerializerContext(Utils::makeItemTypeDictionary());
	}

	public function getServerAddress() : InternetAddress{
		return $this->serverAddress;
	}

	public function getClient() : Client{
		return $this->client;
	}

	public function getConnection() : RakNetConnection{
		return $this->connection;
	}

	public function getCompressor() : Compressor{
		return $this->compressor;
	}

	public function getPlayer() : ?Player{
		return $this->player;
	}

	public function getKeyPair() : KeyPair{
		return $this->keyPair;
	}

	public function getCipher() : ?EncryptionContext{
		return $this->cipher;
	}

	public function isLoggedIn() : bool{
		return $this->loggedIn;
	}

	public function update() : void{
		$this->connection->update();
	}

	public function actuallyConnect() : void{
		$this->connection = new RakNetConnection($this, $this->logger, self::MTU);
		$this->sender = new ClientPacketSender($this->connection);
		$this->handler = new PreSpawnPacketHandler($this);
	}

	public function getHandler() : ?PacketHandler{
		return $this->handler;
	}

	public function setHandler(?PacketHandler $handler) : void{
		$this->handler = $handler;

		if($this->handler !== null){
			$this->handler->setUp();
			$this->logger->debug("A new packet handler has been set (".get_class($handler).")");
		}
	}

	public function createPlayer(StartGamePacket $packet) : void{
		if($this->player !== null){
			throw new \LogicException("Player is already created!");
		}
		$this->player = new Player($this, $this->loginInfo, $packet, $packet->actorRuntimeId, new Location($packet->playerPosition->x, $packet->playerPosition->y, $packet->playerPosition->z, null,$packet->yaw, $packet->pitch));

		$this->logger->info("Player was created, eid: ".$this->client->getId());
	}

	public function TextPacket(TextPacket $packet) : void{
		if($packet->type === TextPacket::TYPE_TRANSLATION or $packet->type === TextPacket::TYPE_RAW){
			$this->logger->info((string) $packet->message);
		}


	}

	public function startEncryption(string $handshakeJwt) : void{
		if($this->cipher !== null){
			throw new \LogicException("Encryption is already started!");
		}

		[$header, $body] = JwtUtils::parse($handshakeJwt);

		$remotePub = JwtUtils::parseDerPublicKey(base64_decode($header["x5u"]));

		$this->keyPair->setRemotePub($remotePub);

		$sharedSecret = EncryptionUtils::generateSharedSecret($this->keyPair->getLocalPriv(), $remotePub);
		$encryptionKey = EncryptionUtils::generateKey($sharedSecret, base64_decode($body["salt"]));

		$this->cipher = EncryptionContext::fakeGCM($encryptionKey);

		$this->logger->debug("Encryption was started, key: ".bin2hex($encryptionKey));
	}

	public function handleEncoded(string $payload) : void{
		if($this->cipher !== null){
			$payload = $this->cipher->decrypt($payload);
		}

		$stream = new PacketBatch($this->compressor?->decompress($payload) ?? $payload);
		foreach($stream->getPackets($this->packetPool, $this->serializerContext, 500) as [$packet, $buffer]){
			if($packet !== null){
				$this->handleDataPacket($packet, $buffer);
			}
		}
	}

	public function handleDataPacket(Packet $packet, string $buffer) : void{
		if(!($packet instanceof ClientboundPacket)){
			throw new PacketHandlingException("Unexpected non-clientbound packet");
		}

		try{
			$packet->decode(PacketSerializer::decoder($buffer, 0, $this->serializerContext));
		}catch(\Throwable $e){
			$this->logger->logException($e);
			return;
		}

		if($this->handler !== null){
			$packet->handle($this->handler);
		}

		foreach($this->client->getDataPacketHandlers() as $handler){
			$handler($packet);
		}

	}

	public function close(){
		$this->sender->close();
	}

	public function sendDataPacket(ServerboundPacket $packet, bool $immediate = false) : void{
		// if(!$this->loggedIn && !$packet->canBeSentBeforeLogin()){
		// 	throw new \InvalidArgumentException("Attempted to send " . get_class($packet) . " too early");
		// }

		$batch = PacketBatch::fromPackets($this->serializerContext, $packet);
		$payload = $this->compressor?->compress($batch->getBuffer()) ?? $batch->getBuffer();

		if($this->cipher !== null){
			$payload = $this->cipher->encrypt($payload);
		}

		$this->sender->send($payload, $immediate);
	}

	public function processLogin() : void{
		if($this->loggedIn){
			throw new \LogicException("Client already loggedIn!");
		}

		[$chainDataJwt, $clientDataJwt] = $this->buildLoginData();
		$this->sendDataPacket(LoginPacket::create(ProtocolInfo::CURRENT_PROTOCOL, $chainDataJwt, $clientDataJwt));

		$this->loggedIn = true;

		$this->logger->info("LoginPacket was sent, nickname: ".$this->loginInfo->getUsername());
	}

	protected function buildLoginData() : array{
		$localPriv = openssl_pkey_new(["ec" => ["curve_name" => "secp384r1"]]);
		$localPub = JwtUtils::emitDerPublicKey($localPriv);

		$this->keyPair = new KeyPair($localPriv, $localPub);

		$localPub = base64_encode($localPub);

		$header = [
			"alg" => "ES384",
			"x5u" => $localPub
		];

		$chainDataJwt = new JwtChain();
		$chainDataJwt->chain = [JwtUtils::create($header, [
			"exp" => time() + 3600,
			"extraData" => [
				"XUID" => "", //TODO: Xbox auth
				"displayName" => $this->loginInfo->getUsername(),
				"identity" => $this->loginInfo->getUuid()->toString(),
			],
			"identityPublicKey" => $localPub,
			"nbf" => time() - 3600
		], $localPriv)];

		$skin = $this->loginInfo->getSkin();
		$animatedImageData = new ClientDataAnimationFrame();
		$animatedImageData->ImageHeight = 64;
		$animatedImageData->ImageWidth = 32;
		$animatedImageData->Frames = 2.0;
		$animatedImageData->Type = 1;
		$animatedImageData->Image = "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADYkkb/8KVU/+SaSv/Ykkb/5JpK/9iSRv/kmkr/5JpK/+SaSv/kmkr/5JpK/+SaSv/kmkr/5JpK/+SaSv/kmkr/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAPClVP/wpVT/8KVU//ClVP/Ykkb/2JJG/9iSRv/wpVT/2JJG/+SaSv/kmkr/5JpK/+SaSv/kmkr/5JpK/9iSRv8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA8KVU//ClVP/8smT//LJk//ClVP/wpVT/2JJG/+SaSv/Ykkb/2JJG/+q3e//qt3v/6rd7/+q3e//Ykkb/2JJG/wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADkmkr/2JJG/9iSRv/kmkr/8KVU/9iSRv/wpVT/8KVU/9iSRv/twoj/6rd7/+q3e//qt3v/6rd7/+3CiP/Ykkb/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAPClVP/8smT//LJk//yyZP/8smT/8KVU//yyZP/8smT/78ua/+3CiP/qt3v/6rd7/+q3e//qt3v/7cKI/+/Lmv8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA5JpK/9iSRv/kmkr/8KVU//ClVP/kmkr/5JpK//ClVP/vy5r/7cKI/+q3e//qt3v/6rd7/+q3e//twoj/78ua/wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADwpVT/8KVU//ClVP/8smT/5JpK//ClVP/kmkr/5JpK/+/Lmv/twoj/7cKI/+3CiP/twoj/7cKI/+3CiP/vy5r/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAOSaSv/8smT/8KVU//yyZP/wpVT//LJk//yyZP/wpVT/78ua/+/Lmv/vy5r/78ua/+/Lmv/vy5r/78ua/+/Lmv8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAOSaSv/wpVT/8KVU/+SaSv/8smT/5JpK//ClVP/kmkr/5JpK//yyZP/wpVT//LJk/+SaSv/wpVT//LJk/+SaSv/kmkr/5JpK//ClVP/8smT/8KVU/+SaSv/kmkr/8KVU/+SaSv/wpVT/8KVU//ClVP/kmkr/8KVU//ClVP/kmkr/5JpK//yyZP/8smT/8KVU//yyZP/kmkr/8KVU/+SaSv/wpVT//LJk/+SaSv/wpVT/5JpK/+SaSv/wpVT//LJk/+SaSv/wpVT/8KVU//yyZP/8smT/8KVU/+SaSv/8smT//LJk//ClVP/wpVT/8KVU/+SaSv/wpVT//LJk/+SaSv/wpVT//LJk//yyZP/kmkr/8KVU/+SaSv/wpVT/8KVU//ClVP/kmkr/8KVU/+SaSv/15MX/9eTF/+SaSv/wpVT/8KVU//yyZP/wpVT/8KVU//ClVP/8smT/5JpK/+SaSv/8smT/8KVU//yyZP/wpVT/5JpK//yyZP/8smT/5JpK//yyZP/8smT/8KVU/+SaSv/wpVT/5JpK/+SaSv/wpVT/8KVU//ClVP/kmkr/9eTF//Xkxf/15MX/9eTF/+SaSv/wpVT/8KVU//yyZP/wpVT/5JpK//ClVP/wpVT/5JpK//ClVP/8smT//LJk/+SaSv/kmkr//LJk//ClVP/Ykkb/5JpK/+SaSv/kmkr/8KVU/+SaSv/15MX/9eTF/+SaSv/15MX/9/fr/yNjLf/15MX/9eTF/yNjLf/39+v/9eTF/+SaSv/8smT/8KVU//yyZP/wpVT/5JpK//ClVP/kmkr/5JpK//yyZP/wpVT/2JJG//ClVP/8smT/5JpK/9iSRv/wpVT/8KVU//ClVP/kmkr/9eTF//Xkxf/15MX/9eTF//Xkxf/15MX/9eTF//Xkxf/15MX/9eTF//Xkxf/15MX/9eTF/+SaSv/8smT/8KVU//yyZP/kmkr/8KVU/+SaSv/wpVT//LJk/+SaSv/Ykkb//LJk//ClVP/kmkr/2JJG/+SaSv/wpVT/2JJG/+SaSv/z27b/9eTF//Xkxf/z27b/89u2//Xkxf/15MX/77ux/++7sf/15MX/9eTF//Pbtv/z27b/89u2//yyZP/kmkr//LJk/9iSRv/wpVT/2JJG//yyZP/wpVT/2JJG//ClVP/8smT/8KVU/9iSRv/kmkr/8KVU/+SaSv/Ykkb/8M+h//DPof/wz6H/8M+h//DPof/wz6H/89u2//Xkxf/15MX/9eTF//Xkxf/z27b/8M+h//DPof/kmkr/8KVU/9iSRv/wpVT/2JJG/+SaSv/Ykkb/8KVU//ClVP/Ykkb/8KVU//ClVP/kmkr/2JJG/+SaSv8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA2JJG//ClVP/kmkr/2JJG/+SaSv/Ykkb/5JpK/+SaSv/kmkr/5JpK/+SaSv/kmkr/5JpK/+SaSv/kmkr/5JpK/wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADwpVT/8KVU//ClVP/wpVT/2JJG/9iSRv/Ykkb/8KVU/9iSRv/kmkr/5JpK/+SaSv/kmkr/5JpK/+SaSv/Ykkb/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAPClVP/wpVT//LJk//yyZP/wpVT/8KVU/9iSRv/kmkr/2JJG/9iSRv/qt3v/6rd7/+q3e//qt3v/2JJG/9iSRv8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA5JpK/9iSRv/Ykkb/5JpK//ClVP/Ykkb/8KVU//ClVP/Ykkb/7cKI/+q3e//qt3v/6rd7/+q3e//twoj/2JJG/wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADwpVT//LJk//yyZP/8smT//LJk//ClVP/8smT//LJk/+/Lmv/twoj/6rd7/+q3e//qt3v/6rd7/+3CiP/vy5r/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAOSaSv/Ykkb/5JpK//ClVP/wpVT/5JpK/+SaSv/wpVT/78ua/+3CiP/qt3v/6rd7/+q3e//qt3v/7cKI/+/Lmv8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA8KVU//ClVP/wpVT//LJk/+SaSv/wpVT/5JpK/+SaSv/vy5r/7cKI/+3CiP/twoj/7cKI/+3CiP/twoj/78ua/wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADkmkr//LJk//ClVP/8smT/8KVU//yyZP/8smT/8KVU/+/Lmv/vy5r/78ua/+/Lmv/vy5r/78ua/+/Lmv/vy5r/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADkmkr/8KVU//ClVP/kmkr//LJk/+SaSv/wpVT/5JpK/+SaSv/8smT/8KVU//yyZP/kmkr/8KVU//yyZP/kmkr/5JpK/+SaSv/wpVT//LJk//ClVP/kmkr/5JpK//ClVP/kmkr/8KVU//ClVP/wpVT/5JpK//ClVP/wpVT/5JpK/+SaSv/8smT//LJk//ClVP/8smT/5JpK//ClVP/kmkr/8KVU//yyZP/kmkr/8KVU/+SaSv/kmkr/8KVU//yyZP/kmkr/8KVU//ClVP/8smT//LJk//ClVP/kmkr//LJk//yyZP/wpVT/8KVU//ClVP/kmkr/8KVU//yyZP/kmkr/8KVU//yyZP/8smT/5JpK//ClVP/kmkr/8KVU//ClVP/wpVT/5JpK//ClVP/kmkr/9eTF//Xkxf/kmkr/8KVU//ClVP/8smT/8KVU//ClVP/wpVT//LJk/+SaSv/kmkr//LJk//ClVP/8smT/8KVU/+SaSv/8smT//LJk/+SaSv/8smT//LJk//ClVP/kmkr/8KVU/+SaSv/kmkr/8KVU//ClVP/wpVT/5JpK//Xkxf/15MX/9eTF//Xkxf/kmkr/8KVU//ClVP/8smT/8KVU/+SaSv/wpVT/8KVU/+SaSv/wpVT//LJk//yyZP/kmkr/5JpK//yyZP/wpVT/2JJG/+SaSv/kmkr/5JpK//ClVP/kmkr/9eTF//Xkxf/kmkr/9eTF//LdxP/y3cT/9eTF//Xkxf/y3cT/8t3E//Xkxf/kmkr//LJk//ClVP/8smT/8KVU/+SaSv/wpVT/5JpK/+SaSv/8smT/8KVU/9iSRv/wpVT//LJk/+SaSv/Ykkb/8KVU//ClVP/wpVT/5JpK//Xkxf/15MX/9eTF//Xkxf/15MX/9eTF//Xkxf/15MX/9eTF//Xkxf/15MX/9eTF//Xkxf/kmkr//LJk//ClVP/8smT/5JpK//ClVP/kmkr/8KVU//yyZP/kmkr/2JJG//yyZP/wpVT/5JpK/9iSRv/kmkr/8KVU/9iSRv/kmkr/89u2//Xkxf/15MX/89u2//Pbtv/15MX/9eTF/++7sf/vu7H/9eTF//Xkxf/z27b/89u2//Pbtv/8smT/5JpK//yyZP/Ykkb/8KVU/9iSRv/8smT/8KVU/9iSRv/wpVT//LJk//ClVP/Ykkb/5JpK//ClVP/kmkr/2JJG//DPof/wz6H/8M+h//DPof/wz6H/8M+h//Pbtv/15MX/9eTF//Xkxf/15MX/89u2//DPof/wz6H/5JpK//ClVP/Ykkb/8KVU/9iSRv/kmkr/2JJG//ClVP/wpVT/2JJG//ClVP/wpVT/5JpK/9iSRv/kmkr/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=";
		$animatedImageData->AnimationExpression = 1;

		$test = new ClientDataPersonaSkinPiece();
		$test->PieceId = '8f96d1f8-e9bb-40d2-acc8-eb79746c5d7c';
		$test->PieceType = 'persona_skeleton';
		$test->PackId = '2099de18-429a-465a-a49b-fc4710a17bb3';
		$test->IsDefault = true;
		$test->ProductId = '';

		$PersonaPieces = [
			$test,
			$test,
			$test,
			$test,
			$test,
			$test,
			$test,
			$test,
			$test,
		];

		$hh = new ClientDataPersonaPieceTintColor();
		$hh->PieceType = 'persona_mouth';
		$hh->Colors = [
			'#0',
			'#0',
			"#efbbb1",
			"#0",
		];

		$hh2 = new ClientDataPersonaPieceTintColor();
		$hh2->PieceType = 'persona_eyes';
		$hh2->Colors = [
			'#236224',
			'#0',
			"#0",
			"#0",
		];

		$hh3 = new ClientDataPersonaPieceTintColor();
		$hh3->PieceType = 'persona_hair';
		$hh3->Colors = [
			"#e89d4c",
			'#0',
			"#0",
			"#0",
		];

		$PieceTintColors = [
			$hh,
			$hh2,
			$hh3
		];
		$clientDataJwt = JwtUtils::create($header, [
			"AnimatedImageData" => [], //TODO: Hardcoded value
			"ArmSize" => "wide", //TODO: Hardcoded value
			"CapeData" => "", //TODO: Hardcoded value
			"CapeId" => "", //TODO: Hardcoded value
			"CapeImageHeight" => 0, //TODO: Hardcoded value
			"CapeImageWidth" => 0, //TODO: Hardcoded value
			"CapeOnClassicSkin" => false, //TODO: Hardcoded value
			"ClientRandomId" => $this->client->getId(),
			"CompatibleWithClientSideChunkGen" => true, //TODO: Hardcoded value
			"CurrentInputMode" => 1, //TODO: Hardcoded value
			"DefaultInputMode" => 1, //TODO: Hardcoded value
			"DeviceId" => $this->loginInfo->getDeviceId(),
			"DeviceModel" => $this->loginInfo->getDeviceModel(),
			"DeviceOS" => $this->loginInfo->getDeviceOS(),
			"GameVersion" => ProtocolInfo::MINECRAFT_VERSION_NETWORK,
			"GuiScale" => 0, //TODO: Hardcoded value
			"IsEditorMode" => false, //TODO: Hardcoded value
			"LanguageCode" => $this->loginInfo->getLocale(),
			"OverrideSkin" => false, //TODO: Hardcoded value
			"PersonaPieces" => [], //TODO: Hardcoded value
			"PersonaSkin" => false, //TODO: Hardcoded value
			"PieceTintColors" => [], //TODO: Hardcoded value
			"PlatformOfflineId" => "", //TODO: Hardcoded value
			"PlatformOnlineId" => "", //TODO: Hardcoded value
			"PlayFabId" => "54e5660a3c095fd5", //TODO: Hardcoded value
			"PremiumSkin" => false, //TODO: Hardcoded value
			"SelfSignedId" => "8525f9ff-3031-359a-b1d0-8c3cf903f779", //base64_encode(random_bytes(16)),
			"ServerAddress" => $this->serverAddress->getIp() . ":" . $this->serverAddress->getPort(),
			"SkinAnimationData" => "", //TODO: Hardcoded value
			"SkinColor" => "#0", //TODO: Hardcoded value
			"SkinData" => "AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP/thjn/7YY5/+2GOf/vk1D/75NQ/+2GOf/thjn/7YY5/8ucl//LnJf/y5yX/8ucl//LnJf/y5yX/8ucl//LnJf/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADthjn/7YY5/wAAAAAAAAAA7YY5/+2GOf8AAAAAAAAAAMucl/8AAAAAAAAAAAAAAAAAAAAAy5yX/wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/7YY5/1yGW/90oXP/63gi/+t4Iv/reCL/75NQ/+2GOf/LnJf/y5yX/8ucl//LnJf/y5yX/8ucl//LnJf/y5yX/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADthjn/XIZb/3Shc/8AAAAAAAAAAOt4Iv/vk1D/7YY5/8ucl/8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADLnJf/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/+2GOf9chlv/ZpZl/2aWZf/HXxP/3moV/+t4Iv/thjn/y5yX/8ucl//LnJf/y5yX/8ucl//LnJf/y5yX/8ucl/8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA7YY5/1yGW/8AAAAAAAAAAAAAAAAAAAAA63gi/+2GOf/LnJf/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAy5yX/wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP/thjn/63gi/1yGW/9chlv/3moV/8dfE//reCL/7YY5/8ucl//LnJf/y5yX/8ucl//LnJf/y5yX/8ucl//LnJf/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/7YY5/+t4Iv/eahX/x18T/1yGW//eahX/63gi/+2GOf/LnJf/y5yX//fR0f/30dH/99HR//fR0f/LnJf/y5yX/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/+2GOf/vk1D/63gi/+t4Iv/reCL/63gi/++TUP/thjn/y5yX//fR0f/53t7/+d7e//ne3v/53t7/99HR/8ucl/8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP/thjn/7YY5/+2GOf/vk1D/75NQ/+2GOf/thjn/7YY5/8ucl//30dH/+d7e//zs6//87Ov/+d7e//fR0f/LnJf/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/+Pj4/+vr6//thjn/7YY5/+2GOf/thjn/6+vr//j4+P/LnJf/99HR//ne3v/87Ov//Ozr//ne3v/30dH/y5yX/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA6+vr/wAAAADthjn/7YY5/wAAAADr6+v/AAAAAAAAAADUrKj/AAAAAAAAAAAAAAAAAAAAANSsqP8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADthjn/7YY5/+2GOf/thjn/7YY5/+2GOf/thjn/+Pj4//j4+P/r6+v/7YY5/+2GOf/thjn/7YY5/+vr6//4+Pj/+Pj4/+2GOf/thjn/7YY5/+2GOf/thjn/7YY5/+2GOf/thjn/7YY5/+2GOf/thjn/7YY5/+2GOf/thjn/7YY5/wAAAADthjn/7YY5/wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAOvr6/8AAAAA7YY5/+2GOf8AAAAA6+vr/wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAO2GOf/thjn/AAAAAAAAAADthjn/7YY5/wAAAAAAAAAA7YY5/+2GOf8AAAAA7YY5/+2GOf/thjn/7YY5/+2GOf/thjn/7YY5/+vr6//r6+v/Pj09/+2GOf/thjn/7YY5/+2GOf8+PT3/6+vr/+vr6//thjn/7YY5/+2GOf/thjn/7YY5/+2GOf/thjn/7YY5/+2GOf/thjn/7YY5/+2GOf/thjn/7YY5/+2GOf/thjn/7YY5/wAAAAAAAAAAAAAAAAAAAAAAAAAA6+vr/+vr6/8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADr6+v/6+vr/wAAAAAAAAAAAAAAAAAAAAAAAAAA7YY5/+2GOf/thjn/7YY5/wAAAAAAAAAAAAAAAAAAAADthjn/7YY5/+2GOf/thjn/7YY5/+2GOf/thjn/7YY5/+2GOf/thjn/7YY5/+2GOf/thjn/7YY5/+2GOf/thjn/7YY5/+2GOf/thjn/7YY5/+2GOf/thjn/7YY5/+2GOf/thjn/7YY5/+2GOf/thjn/7YY5/+2GOf/thjn/7YY5/+2GOf/thjn/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADeahX/3moV/95qFf/eahX/3moV/95qFf/eahX/3moV/95qFf/eahX/3moV/95qFf/eahX/3moV/95qFf/eahX/3moV/95qFf/eahX/3moV/95qFf/eahX/3moV/95qFf/eahX/3moV/95qFf/eahX/3moV/95qFf/eahX/3moV/95qFf/eahX/3moV/95qFf/eahX/3moV/95qFf/eahX/3moV/95qFf/eahX/3moV/95qFf/eahX/3moV/95qFf/eahX/3moV/95qFf/eahX/3moV/95qFf/eahX/3moV/95qFf/eahX/3moV/95qFf/eahX/3moV/95qFf/eahX/y5yX/9y8uf/UrKj/5czK/+XMyv/UrKj/3Ly5/8ucl//LnJf/MTAw/zEwMP/twcH/7cHB/zEwMP8xMDD/y5yX/8ucl//cvLn/1Kyo/+XMyv/lzMr/1Kyo/9y8uf/LnJf/y5yX/9y8uf/UrKj/5czK/+XMyv/UrKj/3Ly5/8ucl/8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADt3Nv/MTAw/+3c2//lzMr/MTAw/+3c2/8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAMucl//UrKj/y5yX/9y8uf/cvLn/y5yX/9SsqP8xMDD/MTAw/zEwMP8xMDD/7cHB/+3Bwf8xMDD/MTAw/zEwMP8xMDD/1Kyo/8ucl//cvLn/3Ly5/8ucl//UrKj/y5yX/8ucl//UrKj/y5yX/9y8uf/cvLn/y5yX/9SsqP/LnJf/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADEwMP8xMDD/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAMTAw/zEwMP8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADLnJf/1Kyo/8ucl//UrKj/1Kyo/8ucl//UrKj/MTAw/zEwMP/r2Nv/0bS5//vn5v/75+b/0bS5/+vY2/8xMDD/MTAw/9SsqP/LnJf/1Kyo/9SsqP/LnJf/1Kyo/8ucl//LnJf/1Kyo/8ucl//UrKj/1Kyo/8ucl//UrKj/y5yX/8ucl//UrKj/AAAAAAAAAAAAAAAAAAAAAAAAAADUrKj/1Kyo/wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAANSsqP/UrKj/AAAAAAAAAAAAAAAAAAAAAAAAAADUrKj/y5yX/8ucl//UrKj/AAAAAAAAAAAAAAAAAAAAANSsqP/LnJf/y5yX/8ucl//LnJf/1Kyo/9SsqP/LnJf/y5yX/8ucl//LnJf/99HR//ne3v/87Ov//Ozr//ne3v/30dH/y5yX/8ucl//LnJf/y5yX/9SsqP/UrKj/y5yX/8ucl//LnJf/y5yX/8ucl//LnJf/1Kyo/9SsqP/LnJf/y5yX/8ucl/8AAAAAy5yX/8ucl/8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADUrKj/AAAAAAAAAAAAAAAAAAAAANSsqP8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADLnJf/y5yX/wAAAAAAAAAAy5yX/8ucl/8AAAAAAAAAAMucl//LnJf/AAAAAAAAAP8AAAD/AAAA/wAAAP8rJi7/Misz/ysmLv8yKzP/IB4d/yAeHf8gHh3/IB4d/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/y5yX/8ucl//LnJf/y5yX/8ucl//LnJf/y5yX/8ucl/8rJi7/6Nza/+jc2v/o3Nr/6Nza/+jc2v/o3Nr/KyYu/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/Misz/zIrM/8rJi7/KyYu/zIrM/8rJi7/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/KyYu/zIrM/8rJi7/Misz/yAeHf///fz///38//z08v8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/8ucl//LnJf/y5yX/8ucl//LnJf/y5yX/8ucl//LnJf/KyYu/zIrM/8rJi7/Misz/zIrM/8rJi7/Misz/ysmLv8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/zIrM/8yKzP/KyYu/zIrM//80db/KyYu/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/ysmLv8yKzP/KyYu/zIrM/8gHh3///38///9/P/89PL/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP/LnJf/y5yX/8ucl//53t7/+d7e/8ucl//LnJf/y5yX/ysmLv8yKzP/KyYu/zIrM/8yKzP/KyYu/zIrM/8rJi7/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8yKzP/Misz/ysmLv8yKzP//Nvd/ysmLv8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8rJi7/Misz/ysmLv8yKzP/IB4d///9/P///fz//PTy/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/y5yX/8ucl//LnJf/+d7e//ne3v/LnJf/y5yX/8ucl/8rJi7/6Nza/ysmLv8yKzP/Misz/ysmLv8yKzP/KyYu/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/Misz/zIrM/8rJi7/KyYu/zIrM/8rJi7/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8rJi7/KyYu/ysmLv8rJi7/KyYu/zIrM/8rJi7/Misz/zIrM/8yKzP/Misz/zIrM/8yKzP/KyYu/zIrM/8rJi7/y5yX/8ucl//LnJf/y5yX/8ucl//LnJf/y5yX//ne3v/53t7//////8ucl//LnJf/y5yX/8ucl//LnJf/y5yX/8ucl//LnJf/y5yX/9SsqP/UrKj/y5yX/8ucl//LnJf/Misz/zIrM/8yKzP/Misz/zIrM/8yKzP/KyYu/ysmLv8rJi7/KyYu/ysmLv8rJi7/Misz/zIrM/8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/JCIh/yQiIf8kIiH/JCIh/yQiIf8kIiH/JCIh/2l0Tv9pdE7/IB4d/yAeHf/ge1H/4HtR/9VvTv/ge1H/JCIh/8ucl/8rJi7/KyYu/8ucl//LnJf/1Kyo/8ucl//79/v/+/f7/zIrM/8yKzP/y5yX/8ucl/8rJi7/KyYu/8ucl//LnJf/1Kyo/8ucl//UrKj/1Kyo/8ucl//UrKj/y5yX/zIrM/8yKzP/Misz/zIrM/8yKzP/Misz/ysmLv8rJi7/KyYu/ysmLv8rJi7/KyYu/zIrM/8yKzP/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/yQiIf8kIiH/JCIh/yQiIf8kIiH/JCIh/+B7Uf/Vb07/1W9O/+B7Uf8gHh3/4HtR/+B7Uf/Vb07/4HtR/yQiIf/LnJf/KyYu/ysmLv/LnJf/y5yX/9SsqP/LnJf/ODA3/zgwN/84MDf/1Kyo/ysmLv/LnJf/KyYu/ysmLv/LnJf/y5yX/9SsqP/LnJf/3Ly5/9y8uf/LnJf/1Kyo/8ucl/84MDf/ODA3/zgwN/84MDf/ODA3/zgwN/8rJi7/KyYu/ysmLv8rJi7/KyYu/ysmLv84MDf/ODA3/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8kIiH/JCIh/yQiIf8kIiH/JCIh/yQiIf/ge1H/1W9O/9VvTv/ge1H/IB4d/yAeHf8gHh3/JCIh/yQiIf8kIiH/y5yX/zIrM/8yKzP/y5yX/8ucl//cvLn/1Kyo/zgwN/84MDf/+/f7//v3+/8yKzP/y5yX/zIrM/8yKzP/y5yX/8ucl//cvLn/1Kyo/+HKyf/hysn/1Kyo/9y8uf/LnJf/ODA3/zgwN/84MDf/ODA3/zgwN/84MDf/Misz/zIrM/8yKzP/Misz/zIrM/8yKzP/ODA3/zgwN/8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/JCIh/yQiIf9pdE7/JCIh/yQiIf8kIiH/JCIh/xwaGf8cGhn/HBoZ/xwaGf8cGhn/HBoZ/yQiIf8kIiH/JCIh/9SsqP8yKzP/Misz/9SsqP/UrKj/4crJ/9y8uf84MDf/+/f7//v3+//79/v/+/f7/9SsqP8yKzP/Misz/9SsqP/UrKj/4crJ/9SsqP/t3Nv/4crJ/9SsqP/hysn/1Kyo/zgwN/84MDf/32xU/zgwN/84MDf/32xU/zIrM/8yKzP/Misz/zIrM/8yKzP/Misz/zgwN/84MDf/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/yQiIf/ge1H/1W9O/+B7Uf/ge1H/IB4d/yAeHf8cGhn/HBoZ/xwaGf9pdE7/HBoZ/xwaGf8gHh3/IB4d/yQiIf/UrKj/Misz/zIrM//UrKj/1Kyo/+3c2//cvLn/ODA3//v3+//79/v/+/f7//v3+//UrKj/Misz/zIrM//UrKj/1Kyo/+3c2//cvLn/7dzb/+HKyf/cvLn/7dzb/9SsqP84MDf/ODA3/99sVP/peVv/6Xlb/99sVP8yKzP/Misz/zIrM/8yKzP/Misz/zIrM/84MDf/ODA3/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8kIiH/4HtR/9VvTv/ge1H/4HtR/yQiIf8kIiH/IB4d/yAeHf/ge1H/1W9O/+B7Uf/ge1H/JCIh/yQiIf8kIiH/1Kyo/zIrM/8yKzP/Misz/zIrM//t3Nv/3Ly5/zgwN//30tr/+/f7//v3+//30tr/99La/zIrM/8yKzP/1Kyo/zgwN//t3Nv/3Ly5/+3c2//hysn/3Ly5/+3c2/84MDf/ODA3/zgwN/84MDf/6Xlb/+l5W/84MDf/Misz/zIrM/8yKzP/Misz/zIrM/8yKzP/ODA3/zgwN/8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/JCIh/yQiIf8kIiH/JCIh/yQiIf8kIiH/JCIh/yAeHf8gHh3/4HtR/9VvTv/ge1H/4HtR/yQiIf8kIiH/JCIh/9SsqP8yKzP/Misz/9SsqP/UrKj/4crJ/9SsqP84MDf/ODA3//v3+//79/v/Misz/9SsqP8yKzP/Misz/9SsqP/UrKj/4crJ/9SsqP/t3Nv/4crJ/9SsqP/hysn/1Kyo/zgwN/84MDf/ODA3/zgwN/84MDf/ODA3/zIrM/8yKzP/Misz/zIrM/8yKzP/Misz/zgwN/84MDf/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/yQiIf8kIiH/JCIh/yQiIf8kIiH/JCIh/2l0Tv8gHh3/IB4d/yAeHf8gHh3/IB4d/yAeHf8kIiH/aXRO/yQiIf/UrKj/Misz/zIrM//UrKj/1Kyo/9y8uf/UrKj/ODA3/zgwN/84MDf/+/f7/zIrM//UrKj/Misz/zIrM//UrKj/1Kyo/9y8uf/UrKj/4crJ/+HKyf/UrKj/3Ly5/9SsqP84MDf/ODA3/zgwN/84MDf/ODA3/zgwN/8yKzP/Misz/zIrM/8yKzP/Misz/zIrM/84MDf/ODA3/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP/ge1H/JCIh/yQiIf8kIiH/JCIh/+B7Uf/Vb07/4HtR/+B7Uf8gHh3/IB4d/yAeHf8gHh3/4HtR/9VvTv/ge1H/y5yX/zIrM/8yKzP/y5yX/8ucl//UrKj/ODA3/zgwN/84MDf//////zgwN/8yKzP/y5yX/zIrM/8yKzP/y5yX/8ucl//UrKj/y5yX/9y8uf/cvLn/y5yX/9SsqP/LnJf/ODA3/zgwN/84MDf/ODA3/zgwN/84MDf/Misz/zIrM/8yKzP/Misz/zIrM/8yKzP/ODA3/zgwN/8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/4HtR/yQiIf8kIiH/JCIh/yQiIf/ge1H/1W9O/+B7Uf/ge1H/IB4d/yAeHf8gHh3/IB4d/+B7Uf/Vb07/4HtR/8ucl/8yKzP/Misz/8ucl//LnJf/ODA3/zgwN/84MDf/ODA3/zgwN/84MDf/Misz/8ucl/8yKzP/Misz/8ucl//LnJf/1Kyo/8ucl//UrKj/1Kyo/8ucl//UrKj/y5yX/ysmLv8yKzP/Misz/ysmLv8rJi7/Misz/ysmLv8rJi7/KyYu/ysmLv8rJi7/KyYu/zIrM/8rJi7/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/yAeHf8gHh3/IB4d/yAeHf8gHh3///38///9/P/89PL//PTy//z08v/89PL/IB4d/yAeHf8gHh3/IB4d/yAeHf8rJi7/KyYu/ysmLv8rJi7/KyYu/8ucl/8rJi7/Misz/zIrM/8rJi7/Misz/ysmLv8rJi7/KyYu/ysmLv8rJi7/KyYu/8ucl//LnJf/1Kyo/9SsqP/LnJf/y5yX/ysmLv8rJi7/Misz/zIrM/8rJi7/KyYu/zIrM/8rJi7/KyYu/ysmLv8rJi7/KyYu/ysmLv8yKzP/KyYu/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA//////////8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADLnJf/AAAAAAAAAAAAAAAAAAAAAMucl/8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAJCIh/yQiIf8kIiH/JCIh/yQiIf8kIiH/4HtR/wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACQiIf8kIiH/JCIh/8ucl/8AAAAAAAAAAMucl//LnJf/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAMucl/8AAAAAAAAAAMucl//LnJf/AAAAAAAAAADcvLn/AAAAAAAAAAAAAAAAy5yX/wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACQiIf8kIiH/aXRO/yQiIf8kIiH/JCIh/yQiIf8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAkIiH/JCIh/yQiIf/UrKj/AAAAAAAAAADUrKj/1Kyo/+HKyf8AAAAAAAAAAAAAAAD//////////wAAAADUrKj/AAAAAAAAAADUrKj/1Kyo/9y8uf8AAAAA7dzb/+HKyf8AAAAA3Ly5/9SsqP84MDf/ODA3/+l5W/84MDf/ODA3/+l5W/8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA4MDf/ODA3/wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADt3Nv/AAAAAAAAAABePlD//////14+UP8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADt3Nv/AAAAAO3c2//hysn/AAAAAO3c2/8AAAAAODA3/zgwN//peVv/9YVf//WFX//peVv/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAODA3/zgwN/8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAJCIh/+B7Uf/Vb07/4HtR/+B7Uf8kIiH/JCIh/yAeHf8gHh3/4HtR/9VvTv/ge1H/4HtR/yQiIf8kIiH/JCIh/wAAAAAAAAAAAAAAAAAAAAAAAAAA7dzb/9y8uf8AAAAAAAAAAP//////////AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA7dzb/wAAAADt3Nv/4crJ/wAAAADt3Nv/AAAAAAAAAAAAAAAAAAAAAPWFX//1hV//AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACQiIf8kIiH/JCIh/yQiIf8kIiH/JCIh/yQiIf8gHh3/IB4d/+B7Uf/Vb07/4HtR/+B7Uf8kIiH/JCIh/yQiIf8AAAAAAAAAAAAAAAAAAAAAAAAAAOHKyf/UrKj/AAAAAAAAAAAAAAAA/////wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAOHKyf8AAAAA7dzb/wAAAAAAAAAA4crJ/wAAAAA4MDf/ODA3/zgwN/84MDf/ODA3/zgwN/8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA4MDf/ODA3/wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAkIiH/JCIh/yQiIf8kIiH/JCIh/yQiIf9pdE7/IB4d/yAeHf8gHh3/IB4d/yAeHf8gHh3/JCIh/2l0Tv8kIiH/1Kyo/wAAAAAAAAAA1Kyo/9SsqP/cvLn/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA1Kyo/wAAAAAAAAAA1Kyo/9SsqP/cvLn/AAAAAAAAAAAAAAAAAAAAANy8uf/UrKj/ODA3/zgwN/84MDf/ODA3/zgwN/84MDf/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAODA3/zgwN/8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA4HtR/yQiIf8kIiH/JCIh/yQiIf/ge1H/1W9O/+B7Uf8gHh3/IB4d/yAeHf8gHh3/IB4d/+B7Uf/Vb07/4HtR/8ucl/8AAAAAAAAAAMucl//LnJf/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAMucl/8AAAAAAAAAAMucl//LnJf/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAy5yX/zgwN/84MDf/ODA3/zgwN/84MDf/ODA3/wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADgwN/84MDf/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAOB7Uf8kIiH/JCIh/yQiIf8kIiH/4HtR/9VvTv/ge1H/IB4d/yAeHf8gHh3/IB4d/yAeHf/ge1H/1W9O/+B7Uf8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA4MDf/ODA3/zgwN/84MDf/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAANSsqP8AAAAAAAAAAAAAAAAAAAAA1Kyo/wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA//////////8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADLnJf/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAANSsqP/UrKj/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP8AAAD/AAAA/wAAAP8yKzP/KyYu/zIrM/8rJi7/1W9O/+B7Uf8gHh3/IB4d/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/KyYu/zIrM/8yKzP/KyYu/zIrM/8rJi7/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD/AAAA/wAAAP8AAAD/Misz/ysmLv8yKzP/KyYu//z08v///fz///38/yAeHf8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/ysmLv8yKzP/Misz/ysmLv/80db/Misz/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/wAAAP8AAAD/AAAA/zIrM/8rJi7/Misz/ysmLv/89PL///38///9/P8gHh3/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8rJi7/Misz/zIrM/8rJi7//Nvd/zIrM/8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP8AAAD/AAAA/wAAAP8yKzP/KyYu/zIrM/8rJi7//PTy///9/P///fz/IB4d/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/KyYu/zIrM/8yKzP/KyYu/zIrM/8rJi7/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAyKzP/Misz/zIrM/8yKzP/Misz/ysmLv8yKzP/KyYu/ysmLv8rJi7/KyYu/ysmLv8rJi7/Misz/ysmLv8yKzP/KyYu/ysmLv8rJi7/KyYu/ysmLv8yKzP/Misz/zIrM/8yKzP/Misz/zIrM/8yKzP/Misz/ysmLv8AAAD/AAAA/wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA4HtR/9VvTv/ge1H/IB4d/yAeHf8kIiH/JCIh/2l0Tv9pdE7/JCIh/yQiIf8kIiH/JCIh/yQiIf8kIiH/4HtR/ysmLv8rJi7/KyYu/ysmLv8rJi7/Misz/zIrM/8yKzP/Misz/zIrM/8yKzP/Misz/zIrM/8rJi7/AAAA/wAAAP8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAOB7Uf/Vb07/4HtR/yAeHf8gHh3/JCIh/+B7Uf/Vb07/1W9O/+B7Uf8kIiH/JCIh/yQiIf8kIiH/JCIh/+B7Uf8rJi7/KyYu/ysmLv8rJi7/KyYu/zgwN/84MDf/ODA3/zgwN//fbFT/ODA3/zgwN//fbFT/KyYu/wAAAP8AAAD/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA6Xlb/wAAAAAAAAAA6Xlb/wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAJCIh/+B7Uf/Vb07/1W9O/+B7Uf8kIiH/JCIh/yQiIf8kIiH/JCIh/wAAAAAgHh3/IB4d/yAeHf8gHh3/IB4d/yQiIf/ge1H/1W9O/9VvTv/ge1H/JCIh/yQiIf8kIiH/JCIh/yQiIf8gHh3/Misz/zIrM/8yKzP/Misz/zIrM/84MDf/ODA3/zgwN/84MDf/32xU/+l5W//peVv/32xU/zIrM/8AAAD/AAAA/wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAOl5W//1hV//9YVf/+l5W/8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACQiIf8kIiH/JCIh/yQiIf8kIiH/JCIh/yQiIf8kIiH/aXRO/yQiIf8AAAAAHBoZ/xwaGf8cGhn/HBoZ/xwaGf8kIiH/JCIh/yQiIf8kIiH/JCIh/yQiIf8kIiH/JCIh/2l0Tv8kIiH/HBoZ/zIrM/8yKzP/Misz/zIrM/8yKzP/ODA3/zgwN/84MDf/ODA3/zgwN//peVv/6Xlb/zgwN/8yKzP/AAAA/wAAAP8AAAAAAAAAAAAAAAAAAAAAAAAAADgwN/84MDf/ODA3/zgwN/84MDf/9YVf//WFX/84MDf/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABwaGf8cGhn/HBoZ/xwaGf8cGhn/aXRO/yAeHf8kIiH/JCIh/yQiIf8kIiH/4HtR/+B7Uf/Vb07/4HtR/xwaGf8yKzP/Misz/zIrM/8yKzP/Misz/zgwN/84MDf/ODA3/zgwN/84MDf/ODA3/zgwN/84MDf/Misz/wAAAP8AAAD/AAAAAAAAAAAAAAAAAAAAAAAAAAA4MDf/ODA3/zgwN/84MDf/ODA3/zgwN/84MDf/ODA3/wAAAAAAAAAAAAAAACAeHf8gHh3/IB4d/+B7Uf/ge1H/1W9O/+B7Uf8kIiH/JCIh/yQiIf8kIiH/4HtR/+B7Uf/Vb07/4HtR/yAeHf8gHh3/IB4d/yAeHf/ge1H/4HtR/9VvTv/ge1H/JCIh/yQiIf8kIiH/JCIh/+B7Uf/ge1H/1W9O/+B7Uf8gHh3/Misz/zIrM/8yKzP/Misz/zIrM/84MDf/ODA3/zgwN/84MDf/ODA3/zgwN/84MDf/ODA3/zIrM/8AAAD/AAAA/wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgHh3/IB4d/yAeHf/ge1H/4HtR/9VvTv/ge1H/JCIh/yQiIf8kIiH/JCIh/yQiIf8kIiH/JCIh/yQiIf8gHh3/IB4d/yAeHf8gHh3/4HtR/+B7Uf/Vb07/4HtR/yQiIf8kIiH/JCIh/yQiIf8kIiH/JCIh/yQiIf8kIiH/IB4d/zIrM/8yKzP/Misz/zIrM/8yKzP/ODA3/zgwN/84MDf/ODA3/zgwN/84MDf/ODA3/zgwN/8yKzP/AAAA/wAAAP8AAAAAAAAAAAAAAAAAAAAAAAAAADgwN/84MDf/ODA3/zgwN/84MDf/ODA3/zgwN/84MDf/AAAAAAAAAAAAAAAAIB4d/yAeHf8gHh3/IB4d/yAeHf8kIiH/JCIh/yQiIf8kIiH/aXRO/yQiIf8kIiH/JCIh/yQiIf8kIiH/IB4d/yAeHf8gHh3/IB4d/yAeHf8gHh3/JCIh/yQiIf8kIiH/JCIh/2l0Tv8kIiH/JCIh/yQiIf8kIiH/JCIh/yAeHf8yKzP/Misz/zIrM/8yKzP/Misz/zgwN/84MDf/ODA3/zgwN/84MDf/ODA3/zgwN/84MDf/Misz/wAAAP8AAAD/AAAAAAAAAAAAAAAAAAAAAAAAAAA4MDf/ODA3/zgwN/84MDf/ODA3/zgwN/84MDf/ODA3/wAAAAAAAAAAAAAAAGl0Tv8gHh3/IB4d/yAeHf8gHh3/JCIh/yQiIf/ge1H/4HtR/9VvTv/ge1H/JCIh/yQiIf8kIiH/JCIh/2l0Tv9pdE7/IB4d/yAeHf8gHh3/IB4d/yQiIf8kIiH/4HtR/+B7Uf/Vb07/4HtR/yQiIf8kIiH/JCIh/yQiIf9pdE7/Misz/zIrM/8yKzP/Misz/zIrM/84MDf/ODA3/zgwN/84MDf/ODA3/zgwN/84MDf/ODA3/zIrM/8AAAD/AAAA/wAAAAAAAAAAAAAAAAAAAAAAAAAAODA3/zgwN/84MDf/ODA3/zgwN/84MDf/ODA3/zgwN/8AAAAAAAAAAAAAAADVb07/4HtR/yAeHf8gHh3/IB4d/yQiIf8kIiH/4HtR/+B7Uf/Vb07/4HtR/yQiIf8kIiH/JCIh/+B7Uf/Vb07/1W9O/+B7Uf8gHh3/IB4d/yAeHf8kIiH/JCIh/+B7Uf/ge1H/1W9O/+B7Uf8kIiH/JCIh/yQiIf/ge1H/1W9O/ysmLv8rJi7/KyYu/ysmLv8rJi7/Misz/ysmLv8rJi7/Misz/zIrM/8rJi7/KyYu/zIrM/8rJi7/AAAA/wAAAP8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP//////////AAAAANVvTv/89PL//PTy//z08v/89PL///////////8gHh3/IB4d/yAeHf8gHh3/IB4d/yAeHf8gHh3/4HtR/9VvTv8rJi7/KyYu/ysmLv8rJi7/KyYu/zIrM/8rJi7/KyYu/zIrM/8yKzP/KyYu/ysmLv8yKzP/KyYu/wAAAP8AAAD/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA==", //base64_encode($skin->getSkinData()),
			"SkinGeometryData" => 'ewogICAiZm9ybWF0X3ZlcnNpb24iIDogIjEuMTIuMCIsCiAgICJtaW5lY3JhZnQ6Z2VvbWV0cnkiIDogWwogICAgICB7CiAgICAgICAgICJib25lcyIgOiBbCiAgICAgICAgICAgIHsKICAgICAgICAgICAgICAgIm5hbWUiIDogImJvZHkiLAogICAgICAgICAgICAgICAicGFyZW50IiA6ICJ3YWlzdCIsCiAgICAgICAgICAgICAgICJwaXZvdCIgOiBbIDAuMCwgMjQuMCwgMC4wIF0KICAgICAgICAgICAgfSwKICAgICAgICAgICAgewogICAgICAgICAgICAgICAibmFtZSIgOiAid2Fpc3QiLAogICAgICAgICAgICAgICAicGl2b3QiIDogWyAwLjAsIDEyLjAsIDAuMCBdCiAgICAgICAgICAgIH0sCiAgICAgICAgICAgIHsKICAgICAgICAgICAgICAgImN1YmVzIiA6IFsKICAgICAgICAgICAgICAgICAgewogICAgICAgICAgICAgICAgICAgICAib3JpZ2luIiA6IFsgLTUuMCwgOC4wLCAzLjAgXSwKICAgICAgICAgICAgICAgICAgICAgInNpemUiIDogWyAxMCwgMTYsIDEgXSwKICAgICAgICAgICAgICAgICAgICAgInV2IiA6IFsgMCwgMCBdCiAgICAgICAgICAgICAgICAgIH0KICAgICAgICAgICAgICAgXSwKICAgICAgICAgICAgICAgIm5hbWUiIDogImNhcGUiLAogICAgICAgICAgICAgICAicGFyZW50IiA6ICJib2R5IiwKICAgICAgICAgICAgICAgInBpdm90IiA6IFsgMC4wLCAyNC4wLCAzLjAgXSwKICAgICAgICAgICAgICAgInJvdGF0aW9uIiA6IFsgMC4wLCAxODAuMCwgMC4wIF0KICAgICAgICAgICAgfQogICAgICAgICBdLAogICAgICAgICAiZGVzY3JpcHRpb24iIDogewogICAgICAgICAgICAiaWRlbnRpZmllciIgOiAiZ2VvbWV0cnkuY2FwZSIsCiAgICAgICAgICAgICJ0ZXh0dXJlX2hlaWdodCIgOiAzMiwKICAgICAgICAgICAgInRleHR1cmVfd2lkdGgiIDogNjQKICAgICAgICAgfQogICAgICB9LAogICAgICB7CiAgICAgICAgICJib25lcyIgOiBbCiAgICAgICAgICAgIHsKICAgICAgICAgICAgICAgIm5hbWUiIDogInJvb3QiLAogICAgICAgICAgICAgICAicGl2b3QiIDogWyAwLjAsIDAuMCwgMC4wIF0KICAgICAgICAgICAgfSwKICAgICAgICAgICAgewogICAgICAgICAgICAgICAiY3ViZXMiIDogWwogICAgICAgICAgICAgICAgICB7CiAgICAgICAgICAgICAgICAgICAgICJvcmlnaW4iIDogWyAtNC4wLCAxMi4wLCAtMi4wIF0sCiAgICAgICAgICAgICAgICAgICAgICJzaXplIiA6IFsgOCwgMTIsIDQgXSwKICAgICAgICAgICAgICAgICAgICAgInV2IiA6IFsgMTYsIDE2IF0KICAgICAgICAgICAgICAgICAgfQogICAgICAgICAgICAgICBdLAogICAgICAgICAgICAgICAibmFtZSIgOiAiYm9keSIsCiAgICAgICAgICAgICAgICJwYXJlbnQiIDogIndhaXN0IiwKICAgICAgICAgICAgICAgInBpdm90IiA6IFsgMC4wLCAyNC4wLCAwLjAgXQogICAgICAgICAgICB9LAogICAgICAgICAgICB7CiAgICAgICAgICAgICAgICJuYW1lIiA6ICJ3YWlzdCIsCiAgICAgICAgICAgICAgICJwYXJlbnQiIDogInJvb3QiLAogICAgICAgICAgICAgICAicGl2b3QiIDogWyAwLjAsIDEyLjAsIDAuMCBdCiAgICAgICAgICAgIH0sCiAgICAgICAgICAgIHsKICAgICAgICAgICAgICAgImN1YmVzIiA6IFsKICAgICAgICAgICAgICAgICAgewogICAgICAgICAgICAgICAgICAgICAib3JpZ2luIiA6IFsgLTQuMCwgMjQuMCwgLTQuMCBdLAogICAgICAgICAgICAgICAgICAgICAic2l6ZSIgOiBbIDgsIDgsIDggXSwKICAgICAgICAgICAgICAgICAgICAgInV2IiA6IFsgMCwgMCBdCiAgICAgICAgICAgICAgICAgIH0KICAgICAgICAgICAgICAgXSwKICAgICAgICAgICAgICAgIm5hbWUiIDogImhlYWQiLAogICAgICAgICAgICAgICAicGFyZW50IiA6ICJib2R5IiwKICAgICAgICAgICAgICAgInBpdm90IiA6IFsgMC4wLCAyNC4wLCAwLjAgXQogICAgICAgICAgICB9LAogICAgICAgICAgICB7CiAgICAgICAgICAgICAgICJuYW1lIiA6ICJjYXBlIiwKICAgICAgICAgICAgICAgInBhcmVudCIgOiAiYm9keSIsCiAgICAgICAgICAgICAgICJwaXZvdCIgOiBbIDAuMCwgMjQsIDMuMCBdCiAgICAgICAgICAgIH0sCiAgICAgICAgICAgIHsKICAgICAgICAgICAgICAgImN1YmVzIiA6IFsKICAgICAgICAgICAgICAgICAgewogICAgICAgICAgICAgICAgICAgICAiaW5mbGF0ZSIgOiAwLjUwLAogICAgICAgICAgICAgICAgICAgICAib3JpZ2luIiA6IFsgLTQuMCwgMjQuMCwgLTQuMCBdLAogICAgICAgICAgICAgICAgICAgICAic2l6ZSIgOiBbIDgsIDgsIDggXSwKICAgICAgICAgICAgICAgICAgICAgInV2IiA6IFsgMzIsIDAgXQogICAgICAgICAgICAgICAgICB9CiAgICAgICAgICAgICAgIF0sCiAgICAgICAgICAgICAgICJuYW1lIiA6ICJoYXQiLAogICAgICAgICAgICAgICAicGFyZW50IiA6ICJoZWFkIiwKICAgICAgICAgICAgICAgInBpdm90IiA6IFsgMC4wLCAyNC4wLCAwLjAgXQogICAgICAgICAgICB9LAogICAgICAgICAgICB7CiAgICAgICAgICAgICAgICJjdWJlcyIgOiBbCiAgICAgICAgICAgICAgICAgIHsKICAgICAgICAgICAgICAgICAgICAgIm9yaWdpbiIgOiBbIDQuMCwgMTIuMCwgLTIuMCBdLAogICAgICAgICAgICAgICAgICAgICAic2l6ZSIgOiBbIDQsIDEyLCA0IF0sCiAgICAgICAgICAgICAgICAgICAgICJ1diIgOiBbIDMyLCA0OCBdCiAgICAgICAgICAgICAgICAgIH0KICAgICAgICAgICAgICAgXSwKICAgICAgICAgICAgICAgIm5hbWUiIDogImxlZnRBcm0iLAogICAgICAgICAgICAgICAicGFyZW50IiA6ICJib2R5IiwKICAgICAgICAgICAgICAgInBpdm90IiA6IFsgNS4wLCAyMi4wLCAwLjAgXQogICAgICAgICAgICB9LAogICAgICAgICAgICB7CiAgICAgICAgICAgICAgICJjdWJlcyIgOiBbCiAgICAgICAgICAgICAgICAgIHsKICAgICAgICAgICAgICAgICAgICAgImluZmxhdGUiIDogMC4yNTAsCiAgICAgICAgICAgICAgICAgICAgICJvcmlnaW4iIDogWyA0LjAsIDEyLjAsIC0yLjAgXSwKICAgICAgICAgICAgICAgICAgICAgInNpemUiIDogWyA0LCAxMiwgNCBdLAogICAgICAgICAgICAgICAgICAgICAidXYiIDogWyA0OCwgNDggXQogICAgICAgICAgICAgICAgICB9CiAgICAgICAgICAgICAgIF0sCiAgICAgICAgICAgICAgICJuYW1lIiA6ICJsZWZ0U2xlZXZlIiwKICAgICAgICAgICAgICAgInBhcmVudCIgOiAibGVmdEFybSIsCiAgICAgICAgICAgICAgICJwaXZvdCIgOiBbIDUuMCwgMjIuMCwgMC4wIF0KICAgICAgICAgICAgfSwKICAgICAgICAgICAgewogICAgICAgICAgICAgICAibmFtZSIgOiAibGVmdEl0ZW0iLAogICAgICAgICAgICAgICAicGFyZW50IiA6ICJsZWZ0QXJtIiwKICAgICAgICAgICAgICAgInBpdm90IiA6IFsgNi4wLCAxNS4wLCAxLjAgXQogICAgICAgICAgICB9LAogICAgICAgICAgICB7CiAgICAgICAgICAgICAgICJjdWJlcyIgOiBbCiAgICAgICAgICAgICAgICAgIHsKICAgICAgICAgICAgICAgICAgICAgIm9yaWdpbiIgOiBbIC04LjAsIDEyLjAsIC0yLjAgXSwKICAgICAgICAgICAgICAgICAgICAgInNpemUiIDogWyA0LCAxMiwgNCBdLAogICAgICAgICAgICAgICAgICAgICAidXYiIDogWyA0MCwgMTYgXQogICAgICAgICAgICAgICAgICB9CiAgICAgICAgICAgICAgIF0sCiAgICAgICAgICAgICAgICJuYW1lIiA6ICJyaWdodEFybSIsCiAgICAgICAgICAgICAgICJwYXJlbnQiIDogImJvZHkiLAogICAgICAgICAgICAgICAicGl2b3QiIDogWyAtNS4wLCAyMi4wLCAwLjAgXQogICAgICAgICAgICB9LAogICAgICAgICAgICB7CiAgICAgICAgICAgICAgICJjdWJlcyIgOiBbCiAgICAgICAgICAgICAgICAgIHsKICAgICAgICAgICAgICAgICAgICAgImluZmxhdGUiIDogMC4yNTAsCiAgICAgICAgICAgICAgICAgICAgICJvcmlnaW4iIDogWyAtOC4wLCAxMi4wLCAtMi4wIF0sCiAgICAgICAgICAgICAgICAgICAgICJzaXplIiA6IFsgNCwgMTIsIDQgXSwKICAgICAgICAgICAgICAgICAgICAgInV2IiA6IFsgNDAsIDMyIF0KICAgICAgICAgICAgICAgICAgfQogICAgICAgICAgICAgICBdLAogICAgICAgICAgICAgICAibmFtZSIgOiAicmlnaHRTbGVldmUiLAogICAgICAgICAgICAgICAicGFyZW50IiA6ICJyaWdodEFybSIsCiAgICAgICAgICAgICAgICJwaXZvdCIgOiBbIC01LjAsIDIyLjAsIDAuMCBdCiAgICAgICAgICAgIH0sCiAgICAgICAgICAgIHsKICAgICAgICAgICAgICAgImxvY2F0b3JzIiA6IHsKICAgICAgICAgICAgICAgICAgImxlYWRfaG9sZCIgOiBbIC02LCAxNSwgMSBdCiAgICAgICAgICAgICAgIH0sCiAgICAgICAgICAgICAgICJuYW1lIiA6ICJyaWdodEl0ZW0iLAogICAgICAgICAgICAgICAicGFyZW50IiA6ICJyaWdodEFybSIsCiAgICAgICAgICAgICAgICJwaXZvdCIgOiBbIC02LCAxNSwgMSBdCiAgICAgICAgICAgIH0sCiAgICAgICAgICAgIHsKICAgICAgICAgICAgICAgImN1YmVzIiA6IFsKICAgICAgICAgICAgICAgICAgewogICAgICAgICAgICAgICAgICAgICAib3JpZ2luIiA6IFsgLTAuMTAsIDAuMCwgLTIuMCBdLAogICAgICAgICAgICAgICAgICAgICAic2l6ZSIgOiBbIDQsIDEyLCA0IF0sCiAgICAgICAgICAgICAgICAgICAgICJ1diIgOiBbIDE2LCA0OCBdCiAgICAgICAgICAgICAgICAgIH0KICAgICAgICAgICAgICAgXSwKICAgICAgICAgICAgICAgIm5hbWUiIDogImxlZnRMZWciLAogICAgICAgICAgICAgICAicGFyZW50IiA6ICJyb290IiwKICAgICAgICAgICAgICAgInBpdm90IiA6IFsgMS45MCwgMTIuMCwgMC4wIF0KICAgICAgICAgICAgfSwKICAgICAgICAgICAgewogICAgICAgICAgICAgICAiY3ViZXMiIDogWwogICAgICAgICAgICAgICAgICB7CiAgICAgICAgICAgICAgICAgICAgICJpbmZsYXRlIiA6IDAuMjUwLAogICAgICAgICAgICAgICAgICAgICAib3JpZ2luIiA6IFsgLTAuMTAsIDAuMCwgLTIuMCBdLAogICAgICAgICAgICAgICAgICAgICAic2l6ZSIgOiBbIDQsIDEyLCA0IF0sCiAgICAgICAgICAgICAgICAgICAgICJ1diIgOiBbIDAsIDQ4IF0KICAgICAgICAgICAgICAgICAgfQogICAgICAgICAgICAgICBdLAogICAgICAgICAgICAgICAibmFtZSIgOiAibGVmdFBhbnRzIiwKICAgICAgICAgICAgICAgInBhcmVudCIgOiAibGVmdExlZyIsCiAgICAgICAgICAgICAgICJwaXZvdCIgOiBbIDEuOTAsIDEyLjAsIDAuMCBdCiAgICAgICAgICAgIH0sCiAgICAgICAgICAgIHsKICAgICAgICAgICAgICAgImN1YmVzIiA6IFsKICAgICAgICAgICAgICAgICAgewogICAgICAgICAgICAgICAgICAgICAib3JpZ2luIiA6IFsgLTMuOTAsIDAuMCwgLTIuMCBdLAogICAgICAgICAgICAgICAgICAgICAic2l6ZSIgOiBbIDQsIDEyLCA0IF0sCiAgICAgICAgICAgICAgICAgICAgICJ1diIgOiBbIDAsIDE2IF0KICAgICAgICAgICAgICAgICAgfQogICAgICAgICAgICAgICBdLAogICAgICAgICAgICAgICAibmFtZSIgOiAicmlnaHRMZWciLAogICAgICAgICAgICAgICAicGFyZW50IiA6ICJyb290IiwKICAgICAgICAgICAgICAgInBpdm90IiA6IFsgLTEuOTAsIDEyLjAsIDAuMCBdCiAgICAgICAgICAgIH0sCiAgICAgICAgICAgIHsKICAgICAgICAgICAgICAgImN1YmVzIiA6IFsKICAgICAgICAgICAgICAgICAgewogICAgICAgICAgICAgICAgICAgICAiaW5mbGF0ZSIgOiAwLjI1MCwKICAgICAgICAgICAgICAgICAgICAgIm9yaWdpbiIgOiBbIC0zLjkwLCAwLjAsIC0yLjAgXSwKICAgICAgICAgICAgICAgICAgICAgInNpemUiIDogWyA0LCAxMiwgNCBdLAogICAgICAgICAgICAgICAgICAgICAidXYiIDogWyAwLCAzMiBdCiAgICAgICAgICAgICAgICAgIH0KICAgICAgICAgICAgICAgXSwKICAgICAgICAgICAgICAgIm5hbWUiIDogInJpZ2h0UGFudHMiLAogICAgICAgICAgICAgICAicGFyZW50IiA6ICJyaWdodExlZyIsCiAgICAgICAgICAgICAgICJwaXZvdCIgOiBbIC0xLjkwLCAxMi4wLCAwLjAgXQogICAgICAgICAgICB9LAogICAgICAgICAgICB7CiAgICAgICAgICAgICAgICJjdWJlcyIgOiBbCiAgICAgICAgICAgICAgICAgIHsKICAgICAgICAgICAgICAgICAgICAgImluZmxhdGUiIDogMC4yNTAsCiAgICAgICAgICAgICAgICAgICAgICJvcmlnaW4iIDogWyAtNC4wLCAxMi4wLCAtMi4wIF0sCiAgICAgICAgICAgICAgICAgICAgICJzaXplIiA6IFsgOCwgMTIsIDQgXSwKICAgICAgICAgICAgICAgICAgICAgInV2IiA6IFsgMTYsIDMyIF0KICAgICAgICAgICAgICAgICAgfQogICAgICAgICAgICAgICBdLAogICAgICAgICAgICAgICAibmFtZSIgOiAiamFja2V0IiwKICAgICAgICAgICAgICAgInBhcmVudCIgOiAiYm9keSIsCiAgICAgICAgICAgICAgICJwaXZvdCIgOiBbIDAuMCwgMjQuMCwgMC4wIF0KICAgICAgICAgICAgfQogICAgICAgICBdLAogICAgICAgICAiZGVzY3JpcHRpb24iIDogewogICAgICAgICAgICAiaWRlbnRpZmllciIgOiAiZ2VvbWV0cnkuaHVtYW5vaWQuY3VzdG9tIiwKICAgICAgICAgICAgInRleHR1cmVfaGVpZ2h0IiA6IDY0LAogICAgICAgICAgICAidGV4dHVyZV93aWR0aCIgOiA2NCwKICAgICAgICAgICAgInZpc2libGVfYm91bmRzX2hlaWdodCIgOiAyLAogICAgICAgICAgICAidmlzaWJsZV9ib3VuZHNfb2Zmc2V0IiA6IFsgMCwgMSwgMCBdLAogICAgICAgICAgICAidmlzaWJsZV9ib3VuZHNfd2lkdGgiIDogMQogICAgICAgICB9CiAgICAgIH0sCiAgICAgIHsKICAgICAgICAgImJvbmVzIiA6IFsKICAgICAgICAgICAgewogICAgICAgICAgICAgICAibmFtZSIgOiAicm9vdCIsCiAgICAgICAgICAgICAgICJwaXZvdCIgOiBbIDAuMCwgMC4wLCAwLjAgXQogICAgICAgICAgICB9LAogICAgICAgICAgICB7CiAgICAgICAgICAgICAgICJuYW1lIiA6ICJ3YWlzdCIsCiAgICAgICAgICAgICAgICJwYXJlbnQiIDogInJvb3QiLAogICAgICAgICAgICAgICAicGl2b3QiIDogWyAwLjAsIDEyLjAsIDAuMCBdCiAgICAgICAgICAgIH0sCiAgICAgICAgICAgIHsKICAgICAgICAgICAgICAgImN1YmVzIiA6IFsKICAgICAgICAgICAgICAgICAgewogICAgICAgICAgICAgICAgICAgICAib3JpZ2luIiA6IFsgLTQuMCwgMTIuMCwgLTIuMCBdLAogICAgICAgICAgICAgICAgICAgICAic2l6ZSIgOiBbIDgsIDEyLCA0IF0sCiAgICAgICAgICAgICAgICAgICAgICJ1diIgOiBbIDE2LCAxNiBdCiAgICAgICAgICAgICAgICAgIH0KICAgICAgICAgICAgICAgXSwKICAgICAgICAgICAgICAgIm5hbWUiIDogImJvZHkiLAogICAgICAgICAgICAgICAicGFyZW50IiA6ICJ3YWlzdCIsCiAgICAgICAgICAgICAgICJwaXZvdCIgOiBbIDAuMCwgMjQuMCwgMC4wIF0KICAgICAgICAgICAgfSwKICAgICAgICAgICAgewogICAgICAgICAgICAgICAiY3ViZXMiIDogWwogICAgICAgICAgICAgICAgICB7CiAgICAgICAgICAgICAgICAgICAgICJvcmlnaW4iIDogWyAtNC4wLCAyNC4wLCAtNC4wIF0sCiAgICAgICAgICAgICAgICAgICAgICJzaXplIiA6IFsgOCwgOCwgOCBdLAogICAgICAgICAgICAgICAgICAgICAidXYiIDogWyAwLCAwIF0KICAgICAgICAgICAgICAgICAgfQogICAgICAgICAgICAgICBdLAogICAgICAgICAgICAgICAibmFtZSIgOiAiaGVhZCIsCiAgICAgICAgICAgICAgICJwYXJlbnQiIDogImJvZHkiLAogICAgICAgICAgICAgICAicGl2b3QiIDogWyAwLjAsIDI0LjAsIDAuMCBdCiAgICAgICAgICAgIH0sCiAgICAgICAgICAgIHsKICAgICAgICAgICAgICAgImN1YmVzIiA6IFsKICAgICAgICAgICAgICAgICAgewogICAgICAgICAgICAgICAgICAgICAiaW5mbGF0ZSIgOiAwLjUwLAogICAgICAgICAgICAgICAgICAgICAib3JpZ2luIiA6IFsgLTQuMCwgMjQuMCwgLTQuMCBdLAogICAgICAgICAgICAgICAgICAgICAic2l6ZSIgOiBbIDgsIDgsIDggXSwKICAgICAgICAgICAgICAgICAgICAgInV2IiA6IFsgMzIsIDAgXQogICAgICAgICAgICAgICAgICB9CiAgICAgICAgICAgICAgIF0sCiAgICAgICAgICAgICAgICJuYW1lIiA6ICJoYXQiLAogICAgICAgICAgICAgICAicGFyZW50IiA6ICJoZWFkIiwKICAgICAgICAgICAgICAgInBpdm90IiA6IFsgMC4wLCAyNC4wLCAwLjAgXQogICAgICAgICAgICB9LAogICAgICAgICAgICB7CiAgICAgICAgICAgICAgICJjdWJlcyIgOiBbCiAgICAgICAgICAgICAgICAgIHsKICAgICAgICAgICAgICAgICAgICAgIm9yaWdpbiIgOiBbIC0zLjkwLCAwLjAsIC0yLjAgXSwKICAgICAgICAgICAgICAgICAgICAgInNpemUiIDogWyA0LCAxMiwgNCBdLAogICAgICAgICAgICAgICAgICAgICAidXYiIDogWyAwLCAxNiBdCiAgICAgICAgICAgICAgICAgIH0KICAgICAgICAgICAgICAgXSwKICAgICAgICAgICAgICAgIm5hbWUiIDogInJpZ2h0TGVnIiwKICAgICAgICAgICAgICAgInBhcmVudCIgOiAicm9vdCIsCiAgICAgICAgICAgICAgICJwaXZvdCIgOiBbIC0xLjkwLCAxMi4wLCAwLjAgXQogICAgICAgICAgICB9LAogICAgICAgICAgICB7CiAgICAgICAgICAgICAgICJjdWJlcyIgOiBbCiAgICAgICAgICAgICAgICAgIHsKICAgICAgICAgICAgICAgICAgICAgImluZmxhdGUiIDogMC4yNTAsCiAgICAgICAgICAgICAgICAgICAgICJvcmlnaW4iIDogWyAtMy45MCwgMC4wLCAtMi4wIF0sCiAgICAgICAgICAgICAgICAgICAgICJzaXplIiA6IFsgNCwgMTIsIDQgXSwKICAgICAgICAgICAgICAgICAgICAgInV2IiA6IFsgMCwgMzIgXQogICAgICAgICAgICAgICAgICB9CiAgICAgICAgICAgICAgIF0sCiAgICAgICAgICAgICAgICJuYW1lIiA6ICJyaWdodFBhbnRzIiwKICAgICAgICAgICAgICAgInBhcmVudCIgOiAicmlnaHRMZWciLAogICAgICAgICAgICAgICAicGl2b3QiIDogWyAtMS45MCwgMTIuMCwgMC4wIF0KICAgICAgICAgICAgfSwKICAgICAgICAgICAgewogICAgICAgICAgICAgICAiY3ViZXMiIDogWwogICAgICAgICAgICAgICAgICB7CiAgICAgICAgICAgICAgICAgICAgICJvcmlnaW4iIDogWyAtMC4xMCwgMC4wLCAtMi4wIF0sCiAgICAgICAgICAgICAgICAgICAgICJzaXplIiA6IFsgNCwgMTIsIDQgXSwKICAgICAgICAgICAgICAgICAgICAgInV2IiA6IFsgMTYsIDQ4IF0KICAgICAgICAgICAgICAgICAgfQogICAgICAgICAgICAgICBdLAogICAgICAgICAgICAgICAibmFtZSIgOiAibGVmdExlZyIsCiAgICAgICAgICAgICAgICJwYXJlbnQiIDogInJvb3QiLAogICAgICAgICAgICAgICAicGl2b3QiIDogWyAxLjkwLCAxMi4wLCAwLjAgXQogICAgICAgICAgICB9LAogICAgICAgICAgICB7CiAgICAgICAgICAgICAgICJjdWJlcyIgOiBbCiAgICAgICAgICAgICAgICAgIHsKICAgICAgICAgICAgICAgICAgICAgImluZmxhdGUiIDogMC4yNTAsCiAgICAgICAgICAgICAgICAgICAgICJvcmlnaW4iIDogWyAtMC4xMCwgMC4wLCAtMi4wIF0sCiAgICAgICAgICAgICAgICAgICAgICJzaXplIiA6IFsgNCwgMTIsIDQgXSwKICAgICAgICAgICAgICAgICAgICAgInV2IiA6IFsgMCwgNDggXQogICAgICAgICAgICAgICAgICB9CiAgICAgICAgICAgICAgIF0sCiAgICAgICAgICAgICAgICJuYW1lIiA6ICJsZWZ0UGFudHMiLAogICAgICAgICAgICAgICAicGFyZW50IiA6ICJsZWZ0TGVnIiwKICAgICAgICAgICAgICAgInBpdm90IiA6IFsgMS45MCwgMTIuMCwgMC4wIF0KICAgICAgICAgICAgfSwKICAgICAgICAgICAgewogICAgICAgICAgICAgICAiY3ViZXMiIDogWwogICAgICAgICAgICAgICAgICB7CiAgICAgICAgICAgICAgICAgICAgICJvcmlnaW4iIDogWyA0LjAsIDExLjUwLCAtMi4wIF0sCiAgICAgICAgICAgICAgICAgICAgICJzaXplIiA6IFsgMywgMTIsIDQgXSwKICAgICAgICAgICAgICAgICAgICAgInV2IiA6IFsgMzIsIDQ4IF0KICAgICAgICAgICAgICAgICAgfQogICAgICAgICAgICAgICBdLAogICAgICAgICAgICAgICAibmFtZSIgOiAibGVmdEFybSIsCiAgICAgICAgICAgICAgICJwYXJlbnQiIDogImJvZHkiLAogICAgICAgICAgICAgICAicGl2b3QiIDogWyA1LjAsIDIxLjUwLCAwLjAgXQogICAgICAgICAgICB9LAogICAgICAgICAgICB7CiAgICAgICAgICAgICAgICJjdWJlcyIgOiBbCiAgICAgICAgICAgICAgICAgIHsKICAgICAgICAgICAgICAgICAgICAgImluZmxhdGUiIDogMC4yNTAsCiAgICAgICAgICAgICAgICAgICAgICJvcmlnaW4iIDogWyA0LjAsIDExLjUwLCAtMi4wIF0sCiAgICAgICAgICAgICAgICAgICAgICJzaXplIiA6IFsgMywgMTIsIDQgXSwKICAgICAgICAgICAgICAgICAgICAgInV2IiA6IFsgNDgsIDQ4IF0KICAgICAgICAgICAgICAgICAgfQogICAgICAgICAgICAgICBdLAogICAgICAgICAgICAgICAibmFtZSIgOiAibGVmdFNsZWV2ZSIsCiAgICAgICAgICAgICAgICJwYXJlbnQiIDogImxlZnRBcm0iLAogICAgICAgICAgICAgICAicGl2b3QiIDogWyA1LjAsIDIxLjUwLCAwLjAgXQogICAgICAgICAgICB9LAogICAgICAgICAgICB7CiAgICAgICAgICAgICAgICJuYW1lIiA6ICJsZWZ0SXRlbSIsCiAgICAgICAgICAgICAgICJwYXJlbnQiIDogImxlZnRBcm0iLAogICAgICAgICAgICAgICAicGl2b3QiIDogWyA2LCAxNC41MCwgMSBdCiAgICAgICAgICAgIH0sCiAgICAgICAgICAgIHsKICAgICAgICAgICAgICAgImN1YmVzIiA6IFsKICAgICAgICAgICAgICAgICAgewogICAgICAgICAgICAgICAgICAgICAib3JpZ2luIiA6IFsgLTcuMCwgMTEuNTAsIC0yLjAgXSwKICAgICAgICAgICAgICAgICAgICAgInNpemUiIDogWyAzLCAxMiwgNCBdLAogICAgICAgICAgICAgICAgICAgICAidXYiIDogWyA0MCwgMTYgXQogICAgICAgICAgICAgICAgICB9CiAgICAgICAgICAgICAgIF0sCiAgICAgICAgICAgICAgICJuYW1lIiA6ICJyaWdodEFybSIsCiAgICAgICAgICAgICAgICJwYXJlbnQiIDogImJvZHkiLAogICAgICAgICAgICAgICAicGl2b3QiIDogWyAtNS4wLCAyMS41MCwgMC4wIF0KICAgICAgICAgICAgfSwKICAgICAgICAgICAgewogICAgICAgICAgICAgICAiY3ViZXMiIDogWwogICAgICAgICAgICAgICAgICB7CiAgICAgICAgICAgICAgICAgICAgICJpbmZsYXRlIiA6IDAuMjUwLAogICAgICAgICAgICAgICAgICAgICAib3JpZ2luIiA6IFsgLTcuMCwgMTEuNTAsIC0yLjAgXSwKICAgICAgICAgICAgICAgICAgICAgInNpemUiIDogWyAzLCAxMiwgNCBdLAogICAgICAgICAgICAgICAgICAgICAidXYiIDogWyA0MCwgMzIgXQogICAgICAgICAgICAgICAgICB9CiAgICAgICAgICAgICAgIF0sCiAgICAgICAgICAgICAgICJuYW1lIiA6ICJyaWdodFNsZWV2ZSIsCiAgICAgICAgICAgICAgICJwYXJlbnQiIDogInJpZ2h0QXJtIiwKICAgICAgICAgICAgICAgInBpdm90IiA6IFsgLTUuMCwgMjEuNTAsIDAuMCBdCiAgICAgICAgICAgIH0sCiAgICAgICAgICAgIHsKICAgICAgICAgICAgICAgImxvY2F0b3JzIiA6IHsKICAgICAgICAgICAgICAgICAgImxlYWRfaG9sZCIgOiBbIC02LCAxNC41MCwgMSBdCiAgICAgICAgICAgICAgIH0sCiAgICAgICAgICAgICAgICJuYW1lIiA6ICJyaWdodEl0ZW0iLAogICAgICAgICAgICAgICAicGFyZW50IiA6ICJyaWdodEFybSIsCiAgICAgICAgICAgICAgICJwaXZvdCIgOiBbIC02LCAxNC41MCwgMSBdCiAgICAgICAgICAgIH0sCiAgICAgICAgICAgIHsKICAgICAgICAgICAgICAgImN1YmVzIiA6IFsKICAgICAgICAgICAgICAgICAgewogICAgICAgICAgICAgICAgICAgICAiaW5mbGF0ZSIgOiAwLjI1MCwKICAgICAgICAgICAgICAgICAgICAgIm9yaWdpbiIgOiBbIC00LjAsIDEyLjAsIC0yLjAgXSwKICAgICAgICAgICAgICAgICAgICAgInNpemUiIDogWyA4LCAxMiwgNCBdLAogICAgICAgICAgICAgICAgICAgICAidXYiIDogWyAxNiwgMzIgXQogICAgICAgICAgICAgICAgICB9CiAgICAgICAgICAgICAgIF0sCiAgICAgICAgICAgICAgICJuYW1lIiA6ICJqYWNrZXQiLAogICAgICAgICAgICAgICAicGFyZW50IiA6ICJib2R5IiwKICAgICAgICAgICAgICAgInBpdm90IiA6IFsgMC4wLCAyNC4wLCAwLjAgXQogICAgICAgICAgICB9LAogICAgICAgICAgICB7CiAgICAgICAgICAgICAgICJuYW1lIiA6ICJjYXBlIiwKICAgICAgICAgICAgICAgInBhcmVudCIgOiAiYm9keSIsCiAgICAgICAgICAgICAgICJwaXZvdCIgOiBbIDAuMCwgMjQsIC0zLjAgXQogICAgICAgICAgICB9CiAgICAgICAgIF0sCiAgICAgICAgICJkZXNjcmlwdGlvbiIgOiB7CiAgICAgICAgICAgICJpZGVudGlmaWVyIiA6ICJnZW9tZXRyeS5odW1hbm9pZC5jdXN0b21TbGltIiwKICAgICAgICAgICAgInRleHR1cmVfaGVpZ2h0IiA6IDY0LAogICAgICAgICAgICAidGV4dHVyZV93aWR0aCIgOiA2NCwKICAgICAgICAgICAgInZpc2libGVfYm91bmRzX2hlaWdodCIgOiAyLAogICAgICAgICAgICAidmlzaWJsZV9ib3VuZHNfb2Zmc2V0IiA6IFsgMCwgMSwgMCBdLAogICAgICAgICAgICAidmlzaWJsZV9ib3VuZHNfd2lkdGgiIDogMQogICAgICAgICB9CiAgICAgIH0KICAgXQp9Cg==', //TODO: Hardcoded value
			"SkinGeometryDataEngineVersion" => "MC4wLjA=", //TODO: Hardcoded value
			"SkinId" => 'Custom19bd753a-5328-3c64-9f47-3b360dacf95f', //$skin->getSkinId(),
			"SkinImageHeight" => 64, //TODO: Hardcoded value
			"SkinImageWidth" => 64, //TODO: Hardcoded value
			"SkinResourcePatch" => 'ewogICAiZ2VvbWV0cnkiIDogewogICAgICAiZGVmYXVsdCIgOiAiZ2VvbWV0cnkuaHVtYW5vaWQuY3VzdG9tIgogICB9Cn0K', //base64_encode(json_encode(["geometry" => ["default" => "geometry.humanoid.custom"]])),
			"ThirdPartyName" => $this->loginInfo->getUsername(), //TODO: Hardcoded value
			"ThirdPartyNameOnly" => false, //TODO: Hardcoded value
			"TrustedSkin" => true, //TODO: Hardcoded value
			"UIProfile" => 0 //TODO: Hardcoded value
		], $localPriv);

		return [$chainDataJwt, $clientDataJwt];
	}

	public function setCompressor(?Compressor $compressor) : NetworkSession{
		$this->compressor = $compressor;
		return $this;
	}
}